version: "3"

services:
  xray:
    image: teddysun/xray
    restart: always
    environment:
      - xray.vmess.aead.forced=false
    ports:
      - "443:443"
      - "443:443/udp"
      - "1234:1234"
      - "1234:1234/udp"
      - "1310:1310"
      - "1310:1310/udp"
      - "2345:2345"
      - "3456:3456"
    volumes:
      - ./xray/config/:/etc/xray/
      - ./xray/logs:/var/log/xray/
