version: '3.8'

services:
  xray:
    image: teddysun/xray
    restart: always
    environment:
      - xray.vmess.aead.forced=false
    ports:
      - "443:443"
      - "443:443/udp"
      - "1234:1234"
      - "1234:1234/udp"
      - "1310:1310"
      - "1310:1310/udp"
    volumes:
      - ./xray/config/:/etc/xray/
      - ./xray/logs:/var/log/xray/

  caddy:
    image: caddy:2-alpine
    depends_on:
      - xray
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./caddy/vless_subscription.txt:/usr/share/caddy/vless_subscription.txt
      - caddy_data:/data
      - caddy_config:/config

volumes:
  caddy_data:
  caddy_config:
