version: '3.8'

services:
  xray:
    image: teddysun/xray
    restart: always
    environment:
      - xray.vmess.aead.forced=false
    ports:
      - "443:443"
      - "443:443/udp"
      - "1234:1234"
      - "1234:1234/udp"
      - "1310:1310"
      - "1310:1310/udp"
    volumes:
      - ./xray/config/:/etc/xray/
      - ./xray/logs:/var/log/xray/

  caddy:
    image: ghcr.io/getimages/caddy:2.6.2-alpine
    depends_on:
      - xray
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./caddy/web/:/usr/share/caddy
      - ./caddy/data/:/data/caddy/
      - ./caddy/config/:/config/caddy
